planning_pipelines:
  pipeline_names: ["ompl"]

plan_request_params:
  planning_pipeline: ompl
  planning_time: 5.0
  planning_attempts: 5
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0